# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "aws"
  config.vm.provider :aws do | aws, override |
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.ami = "ami-e075ae97"
    aws.region = "eu-west-1"
    aws.instance_type = "t1.micro"
    aws.security_groups = [ "dev_infra-jenkins_master_lts-CentOS_6.5-x86_64" ]
    aws.tags = {  Name: "dev_infra-jenkins_master_lts-CentOS_6.5-x86_64" }
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = "~/.ssh/dev_infra_key"
  end
end
