# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box_url = "https://jacderida-vagrant-boxes.s3.amazonaws.com/base_server-CentOS-6.5-x86_64.box"
  config.vm.box = "base_server-CentOS-6.5-x86_64.box"
  config.vm.network :private_network, ip: "192.168.56.103"
end
