---
# These passwords will be changed and secured later, using hiera-gpg.
profile::database::admin_password: ajSV5@\,^Uqq6,Z
profile::database::dbserver: placeholder
profile::database::jira_dbuser_password: b7>*£9u?6BqR7Pw
profile::database::stash_dbuser_password: uF9f4~[Z~,e5vQ
