# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "aws"
  config.vm.synced_folder "../../hiera", "/etc/puppet/hieradata"
  config.vm.synced_folder "../../files", "/etc/puppet/files"
  config.vm.provision "shell", inline: "cp /etc/puppet/files/fileserver.conf /etc/puppet"
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file = "jira.pp"
    puppet.module_path = "../../modules"
    puppet.hiera_config_path = "hiera.yaml"
    puppet.facter = { "environment" => "development" }
    puppet.options = "--verbose --debug"
  end
  config.vm.provider :aws do | aws, override |
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.ami = "ami-76bb1e01"
    aws.region = "eu-west-1"
    aws.instance_type = "m1.small"
    aws.security_groups = [ "dev_infra-base_box-aws-CentOS_6.5-x86_64" ]
    aws.tags = {  Name: "jira_install_6.2.7-CentOS_6.5-x86_64" }
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = "~/.ssh/dev_infra_key"
  end
end
